spring:
  profiles:
    active: dev
  application:
    name: bank-account
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  devtools:
    restart:
      enabled: true

server:
  port: 8080